= Externalized Configuration - Spring Boot Booster

IMPORTANT: While you can run and interact with this booster on localhost, you cannot take advantage of using externalized configuration with this booster without using OpenShift. For more details on using this booster with a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:http://launcher.fabric8.io/docs/spring-boot-runtime.html[Spring Boot Runtime Guide].

IMPORTANT: This booster requires Java 8 JDK or greater and Maven 3.3.x or greater.



== Running the Booster Locally
To run this booster on your local host:

[source,bash,options="nowrap",subs="attributes+"]
----
$ unzip multiline-log.zip

$ cd multiline-log

$ mvn spring-boot:run
----

== Interacting with the Booster Locally
To interact with your booster while its running, use the form at `http://localhost:8080` or the `curl` command:

[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080/api/greeting
{"content":"Hello, World!"}

$ curl http://localhost:8080/api/greeting?name=Sarah
{"content":"Hello, Sarah!"}
----

== Running the Booster on a Single-node OpenShift Cluster
If you have a single-node OpenShift cluster, such as Minishift or Red Hat Container Development Kit, link:http://launcher.fabric8.io/docs/minishift-installation.html[installed and running], you can also deploy your booster there. A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

To deploy your booster to a running single-node OpenShift cluster:

. Log in and create your project.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer

$ oc new-project MY_PROJECT_NAME
----

. Be sure that view access rights for the service account are added before deploying your booster using: `oc policy add-role-to-user view -n $(oc project -q) -z default`.

. Navigate to the root directory of your booster.

. Deploy your ConfigMap configuration using `application.yml`.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create configmap app-config --from-file=application.yml
----

. Deploy your booster.
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift
----


== Interacting with the Booster on a Single-node OpenShift Cluster

To interact with your booster while it's running on a Single-node OpenShift Cluster, you first need to obtain it's URL:

[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route booster-configmap-spring-boot -o jsonpath={$.spec.host}

booster-configmap-spring-boot-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME
----

You can use the form at your application's url or you can use the `curl` command:

[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://booster-configmap-spring-boot-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/greeting
{"content":"Hello World from a ConfigMap!"}

$ curl http://booster-configmap-spring-boot-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/greeting?name=Sarah
{"content":"Hello Sarah from a ConfigMap!"}
----

== More Information
You can learn more about this booster and the Spring Boot runtime in the link:http://launcher.fabric8.io/docs/spring-boot-runtime.html[Spring Boot Runtime Guide].

NOTE: Run the set of integration tests included with this booster using `mvn clean verify -Popenshift,openshift-it`.
